services:
  postgreSQL:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi-container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgreSQL
    environment:
      DATABASE_URL: postgresql://postgreSQL:5432/dev

volumes:
  postgres_data: