services:
  postgreSQL:
    image: postgres
    restart: always
    ports:
      - 8080:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi-container:
    image: fastapi-image:latest
    ports:
      - 443:443
    depends_on:
      - postgreSQL
    environment:
      DATABASE_URL: postgresql://postgreSQL:5432/dev

volumes:
  postgres_data: